export default `
<health-rules controller-version="004-005-000-002">
    <health-rule>
        <name>$NAME</name>
        <type>SERVICEENDPOINTS</type>
        <description/>
        <enabled>true</enabled>
        <is-default>false</is-default>
        <always-enabled>true</always-enabled>
        <duration-min>30</duration-min>
        <wait-time-min>30</wait-time-min>
        <affected-entities-match-criteria>
            <affected-add-match-criteria>
                <type>SPECIFIC_ADDS</type>
                <application-diagnostic-data-list>
                    <application-diagnostic-data>
                        <name>$SENAME</name>
                        <type>SERVICE_ENDPOINT</type>
                        <entity>
                            <entity-type>APPLICATION_COMPONENT</entity-type>
                            <application-component>$TIERNAME</application-component>
                        </entity>
                    </application-diagnostic-data>
                </application-diagnostic-data-list>
                <add-types>
                    <add-type>SERVICE_ENDPOINT</add-type>
                </add-types>
            </affected-add-match-criteria>
        </affected-entities-match-criteria>
        <critical-execution-criteria>
            <entity-aggregation-scope>
                <type>ANY</type>
                <value>0</value>
            </entity-aggregation-scope>
            <policy-condition>
                <type>boolean</type>
                <operator>AND</operator>
                <condition1>
                    <type>leaf</type>
                    <display-name>Condition 1</display-name>
                    <condition-value-type>BASELINE_STANDARD_DEVIATION</condition-value-type>
                    <condition-value>4.0</condition-value>
                    <operator>GREATER_THAN</operator>
                    <condition-expression/>
                    <use-active-baseline>true</use-active-baseline>
                    <trigger-on-no-data>false</trigger-on-no-data>
                    <metric-expression>
                        <type>leaf</type>
                        <function-type>VALUE</function-type>
                        <value>0</value>
                        <is-literal-expression>false</is-literal-expression>
                        <display-name>null</display-name>
                        <metric-definition>
                            <type>LOGICAL_METRIC</type>
                            <logical-metric-name>Average Response Time (ms)</logical-metric-name>
                        </metric-definition>
                    </metric-expression>
                </condition1>
                <condition2>
                    <type>leaf</type>
                    <display-name>Condition 2</display-name>
                    <condition-value-type>ABSOLUTE</condition-value-type>
                    <condition-value>10.0</condition-value>
                    <operator>GREATER_THAN</operator>
                    <condition-expression/>
                    <use-active-baseline>false</use-active-baseline>
                    <trigger-on-no-data>false</trigger-on-no-data>
                    <metric-expression>
                        <type>leaf</type>
                        <function-type>VALUE</function-type>
                        <value>0</value>
                        <is-literal-expression>false</is-literal-expression>
                        <display-name>null</display-name>
                        <metric-definition>
                            <type>LOGICAL_METRIC</type>
                            <logical-metric-name>Calls per Minute</logical-metric-name>
                        </metric-definition>
                    </metric-expression>
                </condition2>
            </policy-condition>
        </critical-execution-criteria>
        <warning-execution-criteria>
            <entity-aggregation-scope>
                <type>ANY</type>
                <value>0</value>
            </entity-aggregation-scope>
            <policy-condition>
                <type>boolean</type>
                <operator>AND</operator>
                <condition1>
                    <type>leaf</type>
                    <display-name>Condition 1</display-name>
                    <condition-value-type>BASELINE_STANDARD_DEVIATION</condition-value-type>
                    <condition-value>3.0</condition-value>
                    <operator>GREATER_THAN</operator>
                    <condition-expression/>
                    <use-active-baseline>true</use-active-baseline>
                    <trigger-on-no-data>false</trigger-on-no-data>
                    <metric-expression>
                        <type>leaf</type>
                        <function-type>VALUE</function-type>
                        <value>0</value>
                        <is-literal-expression>false</is-literal-expression>
                        <display-name>null</display-name>
                        <metric-definition>
                            <type>LOGICAL_METRIC</type>
                            <logical-metric-name>Average Response Time (ms)</logical-metric-name>
                        </metric-definition>
                    </metric-expression>
                </condition1>
                <condition2>
                    <type>leaf</type>
                    <display-name>Condition 2</display-name>
                    <condition-value-type>ABSOLUTE</condition-value-type>
                    <condition-value>5.0</condition-value>
                    <operator>GREATER_THAN</operator>
                    <condition-expression/>
                    <use-active-baseline>false</use-active-baseline>
                    <trigger-on-no-data>false</trigger-on-no-data>
                    <metric-expression>
                        <type>leaf</type>
                        <function-type>VALUE</function-type>
                        <value>0</value>
                        <is-literal-expression>false</is-literal-expression>
                        <display-name>null</display-name>
                        <metric-definition>
                            <type>LOGICAL_METRIC</type>
                            <logical-metric-name>Calls per Minute</logical-metric-name>
                        </metric-definition>
                    </metric-expression>
                </condition2>
            </policy-condition>
        </warning-execution-criteria>
    </health-rule>
</health-rules>
`
