export default ({
  applicationName,
  metricPath,
  entityName,
  entityType = 'APPLICATION_COMPONENT',
}) => [
  {
    seriesType: 'LINE',
    metricType: 'OTHER',
    showRawMetricName: false,
    colorPalette: null,
    name: 'Series 0',
    metricMatchCriteriaTemplate: {
      entityMatchCriteria: null,
      metricExpressionTemplate: {
        metricExpressionType: 'Absolute',
        functionType: 'VALUE',
        displayName: 'null',
        inputMetricText: false,
        inputMetricPath: null,
        metricPath,
        scopeEntity: {
          applicationName,
          entityType,
          entityName,
          scopingEntityType: null,
          scopingEntityName: null,
          subtype: null,
        },
      },
      rollupMetricData: true,
      expressionString: '',
      useActiveBaseline: false,
      sortResultsAscending: false,
      maxResults: 20,
      evaluationScopeType: null,
      baselineName: null,
      applicationName,
      metricDisplayNameStyle: 'DISPLAY_STYLE_AUTO',
      metricDisplayNameCustomFormat: null,
    },
    axisPosition: null,
  },
]
