export default {
  widgetType: 'HealthListWidget',
  title: null,
  height: 50,
  width: 50,
  minHeight: 0,
  minWidth: 0,
  x: 0,
  y: 0,
  label: null,
  description: null,
  drillDownUrl: null,
  useMetricBrowserAsDrillDown: false,
  drillDownActionType: null,
  backgroundColor: 16777215,
  backgroundColors: null,
  backgroundColorsStr: '16777215,16777215',
  color: 4210752,
  fontSize: 12,
  useAutomaticFontSize: false,
  borderEnabled: false,
  borderThickness: 0,
  borderColor: 14408667,
  backgroundAlpha: 1,
  showValues: false,
  formatNumber: null,
  numDecimals: 0,
  removeZeros: null,
  compactMode: false,
  showTimeRange: false,
  renderIn3D: false,
  showLegend: null,
  legendPosition: null,
  legendColumnCount: null,
  startTime: null,
  endTime: null,
  minutesBeforeAnchorTime: 15,
  isGlobal: true,
  propertiesMap: null,
  dataSeriesTemplates: null,
  applicationReference: {
    applicationName: '1129PCIS_DEV',
    entityType: 'APPLICATION',
    entityName: '1129PCIS_DEV',
    scopingEntityType: null,
    scopingEntityName: null,
    subtype: null,
  },
  entityReferences: [
    {
      applicationName: '1129PCIS_DEV',
      entityType: 'BUSINESS_TRANSACTION',
      entityName: 'Orion - All Other Traffic',
      scopingEntityType: 'APPLICATION_COMPONENT',
      scopingEntityName: 'tomcat-api1-PCIS',
      subtype: 'SERVLET',
    },
  ],
  entityType: 'BUSINESS_TRANSACTION',
  entitySelectionType: 'SPECIFIED',
  iconSize: 18,
  iconPosition: 'LEFT',
  showSearchBox: false,
  showList: false,
  showListHeader: false,
  showBarPie: false,
  showPie: true,
  innerRadius: 0,
  aggregationType: 'RATIO',
}
